### ISSUE TITLE
Benchmark results and some doubts

### ISSUE THREAD

**Issue by harikt** [mnapoli/di-benchmark#1]
I noticed the benchmark and was curious and have a look at the code 

``` php
$container->set(Baz::class, $container->lazyNew(Baz::class));
$container->set(Bar::class, $container->lazyNew(Bar::class));
$container->params[Bar::class] = [
    'baz' => $container->lazyGet(Baz::class),
];

$container->set(Foo::class, $container->lazyNew(Foo::class));
$container->params[Foo::class] = [
    'bar' => $container->lazyGet(Bar::class),
    'baz' => $container->lazyGet(Baz::class),
];

$container->set('abc', $container->lazyNew(Bar::class));
$container->params['abc'] = [
    'baz' => $container->lazyGet('bcd'),
];
$container->set('bcd', $container->lazyNew(Baz::class));
$container->set('cde', $container->lazyNew(Foo::class));
$container->params['cde'] = [
    'bar' => $container->lazyGet('abc'),
    'baz' => $container->lazyGet('bcd'),
];


for ($i = 0; $i < 50; $i++) {
    $container->get(Foo::class);
}
for ($i = 0; $i < 10; $i++) {
    $container->has('cde');
}
for ($i = 0; $i < 50; $i++) {
    $container->get('cde');
}

echo "Hello world";
```

To my understanding `<Classname>::class` is the only dependency that made you write in composer as php 5.5 .

I changed all the `::class` to normal string value. The above code was also changed to 

``` php
$container->params['Benchmark\Fixture\Bar'] = [
    'baz' => $container->lazyNew('Benchmark\Fixture\Baz'),
];

$container->params['Benchmark\Fixture\Foo'] = [
    'bar' => $container->lazyNew('Benchmark\Fixture\Bar'),
    'baz' => $container->lazyNew('Benchmark\Fixture\Baz'),
];

$container->set('abc', $container->lazyNew('Benchmark\Fixture\Bar'));
$container->set('bcd', $container->lazyNew('Benchmark\Fixture\Baz'));
$container->set('cde', $container->lazyNew('Benchmark\Fixture\Foo'));
$container->set('Benchmark\Fixture\Foo', $container->lazyNew('Benchmark\Fixture\Foo'));

for ($i = 0; $i < 50; $i++) {    
    $container->get('Benchmark\Fixture\Foo');
}
for ($i = 0; $i < 10; $i++) {
    $container->has('cde');
}
for ($i = 0; $i < 50; $i++) {
    $container->get('cde');
}

echo "Hello world";
```

I am not sure why we need to assign two different names to `$container->set`

``` php
$container->set('cde', $container->lazyNew('Benchmark\Fixture\Foo'));
$container->set('Benchmark\Fixture\Foo', $container->lazyNew('Benchmark\Fixture\Foo'));
```

Did a benchmark test and these are the results I got for aura di v1 and v2

``` bash
PHP-DI
Time per request:       28.612 [ms] (mean)

PHP-DI compiled
Time per request:       12.451 [ms] (mean)

Symfony
Time per request:       16.504 [ms] (mean)

Symfony compiled
Time per request:       40.957 [ms] (mean)

Aura v1 
Time per request:       7.696 [ms] (mean)
```

for v2

``` bash
PHP-DI
Time per request:       30.145 [ms] (mean)

PHP-DI compiled
Time per request:       12.682 [ms] (mean)

Symfony
Time per request:       16.365 [ms] (mean)

Symfony compiled
Time per request:       40.205 [ms] (mean)

Aura v2 
Time per request:       7.030 [ms] (mean)
```

I will open the PR so we can see the code change. I was wondering why the symfony compilled went below the normal one though.

**Comment by mnapoli** [comment]
Hi Hari,

There are several reasons for PHP 5.5:
- this is not a library, there is no reason to bother being compatible with older versions, not a lot of people will want to run it (unlike a library) and `::class` is extremely practical
- this is a benchmark, you generally just want to benchmark the latest version of PHP, else you introduce something that varies (the PHP version) and complicate results
- PHP 5.5 has the built-in opcache, which is crucial here because there is some I/O

Now I must say a big fat warning: this benchmark is bullshit. After trying a lot to benchmark DI containers, I have to say this is 1) probably pointless and 2) extremely difficult.

It is pointless because all optimized/compiled container roughly have the same performances (on my results), with differences like a ms for a thousands calls, so this is completely insignificant in a real application. But a benchmark is still a bit interesting for me for example to compare compiled and uncompiled PHP-Di.

So there is problem 2: it is very difficult. Your results prove it, they are very different from mine. The main problem is that everything relies a lot on the opcache (because compiled container `require` one large/many small compiled file) and to have opcache working 100% you need to run the test in a webserver. I first started benchmarking with CLI but opcache didn't seem to run.

So now it all runs behind Apache, but the response time are so small it ended up benchmarking Apache and HTTP instead. So I tried to "slow" down the web pages by having more and more iterations (i.e. `get` more entries) but this has come to a point where it's an unrealistic behavior. And the response times are still too small to benchmark with a webserver, through HTTP.

And if you are using Vagrant, then that's even worse.

Your results with Symfony looks funny, that should be the other way around (compiled Symfony == Aura). Yet another proof that this benchmark is bullshit, I can't explain this :(

If you have any idea on how to improve this, I'd love to hear it.

**Comment by harikt** [comment]
closing this for I have no further ideas :)
